[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "learning-rust"

[workspace]
members = [
    "ownership",
    "lifetimes",
    "vectors",
    "functional_concepts"
]